---
# Main Ansible playbook for deploying Supabase development environment
# This playbook will:
# 1. Set up the server environment
# 2. Deploy the Supabase Docker stack
# 3. Configure services and security

- hosts: supabase_dev
  become: yes
  vars:
    app_user: ubuntu
    app_directory: /opt/supabase-dev
    supabase_version: latest
    environment: development

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - docker
    - supabase-dev
    - security

  post_tasks:
    - name: Display deployment information
      debug:
        msg: |
          🚀 Supabase Development Environment Deployed Successfully!
          
          Access URLs:
          - Frontend: http://{{ ansible_default_ipv4.address }}:3000
          - Supabase Studio: http://{{ ansible_default_ipv4.address }}:3001  
          - Supabase API: http://{{ ansible_default_ipv4.address }}:8000
          - PostgreSQL: {{ ansible_default_ipv4.address }}:5432
          
          SSH Access:
          ssh -i ~/.ssh/your-key ubuntu@{{ ansible_default_ipv4.address }}
          
          Manage Services:
          sudo systemctl start supabase-dev.service
          sudo systemctl stop supabase-dev.service
          sudo systemctl status supabase-dev.service
          
          View Logs:
          cd {{ app_directory }} && docker-compose logs -f